CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY NOT NULL,
surname VARCHAR(50) NOT NULL,
name VARCHAR(50) NOT NULL,
middle_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_qr_codes (
id SERIAL PRIMARY KEY NOT NULL,
user_id INT,
uuid UUID,
FOREIGN KEY (user_id) REFERENCES users (id)
);


